import Event from '@/models/event';

export function createEvent(fields: object = {}): Event {
  return new Event(Object.assign({
      code: 'F000',
      title: 'Mock Event',
      description: 'An autogenerated mock event',
      system: '',
      presenters: '',
      authors: '',
      start_time: '2020-11-01 09:00',
      end_time: '2020-11-01 10:00',
      filled: false,
      hi_test: false,
      test_type: '',
      tags: '',
    },
    fields));
}

