name: Scraper CI

on:
  push:
    branches:
      - master
    paths:
      - scraper/**
      - .github/workflows/scraper.yml

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Setup
      working-directory: scraper
      run: |
        rustup toolchain install nightly
        rustup default nightly
    - name: Build
      working-directory: scraper
      run: cargo build --verbose
    - name: Run tests
      working-directory: scraper
      run: cargo test --verbose
