name: Scraper CI

on:
  push:
    branches:
      - master
    paths:
      - 'scraper/**'
      - '.github/workflows/scraper.yml'

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Use rust nightly
      run: |
        rustup toolchain install nightly
        rustup default nightly
      working-directory: scraper
    - name: Build scraper
      run: cargo build --verbose
      working-directory: scraper
    - name: Run tests
      run: cargo test --verbose
      working-directory: scraper
