name: Website deploy

on:
  push:
    branches: 
      - master
    paths:
      - 'site/**/'
      - './github/workflows/site.yml'

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [13.x]

    steps:
    - uses: actions/checkout@v1
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - name: install dependencies
      run: npm ci
      working-directory: site
      env:
        CI: true
    - name: test
      run: npm run test:unit
      working-directory: site
      env:
        CI: true
    - name: build
      run: npm run build
      working-directory: site
      env:
        CI: true
    - name: restore settings.json
      run: git checkout origin/gh-pages:settings.json > settings.json
      working-directory: site/dist
      env:
        CI: true
        # Deploy to local repo
    - name: deploy
      uses: s0/git-publish-subdir-action@v2.0.0
      env:
        REPO: self
        BRANCH: gh-pages
        FOLDER: site/dist
